### ISSUE TITLE
Search function in NavBar

### ISSUE THREAD

**Issue by Metin74** [digital-peace-talks/DPT-server#12]
**Is your feature request related to a problem? Please describe.**
Search function searching for terms

**Describe the solution you'd like**
A function that allows you to search for terms in the topics

**Describe alternatives you've considered**
The topics are displayed in which the term was searched for is found

**Additional context**
Next setting options for the search function?

**Comment by MartinDPT** [comment]
search implemented.
input field; hit return 4 search; hit close-button to close search-form.
