### ISSUE TITLE
"home" could become "go back" once I am inside a topic

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#14]
It is the same function, but would feel more natural.

**Comment by MartinDPT** [comment]
but, but, but... there is only one place the "home" button takes you to the home ... Opinions.
Also... it is the symbol of a house... nothing says more "go back/ go home" then a house or ...
... a arrow pointing to the left. and every android-user has this symbol allready, allways, every time.
to cut a long story short: let´s keep the "house" :)
