### ISSUE TITLE
Content icons should also close content boxes

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#16]
**Is your feature request related to a problem? Please describe.**
If I click on the content bar, a content box opens. If I want to close this box, I need to go all the way to the box and click "cancel". 

**Describe the solution you'd like**
I would like to close the content box by clicking a second time on the content bar

**Describe alternatives you've considered**
An "x" on the top right corner could also work

**Comment by Metin74** [comment]
fixed =)
