### ISSUE TITLE
When having a dialogue: move "send" button from left to right hand side

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#17]
**Is your feature request related to a problem? Please describe.**
When I want to send a message in a dialogue, I am always tempted to click on the button on the fare right hand side. But this button is "end dialog", the exact opposite of what I am looking for. 

**Describe the solution you'd like**
"send" should be positioned at the fare right hand side.  

**Describe alternatives you've considered**
to postion the send button as an icon within the typing form? 

**Additional context**
this issue will get worse, once "close window" has been changed to "x" on the top right corner.

**Comment by MartinDPT** [comment]
done! and i close this cause of redundancy. see #4 for more info!
