### ISSUE TITLE
propositions do not trigger notifications

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#20]
**Describe the bug**
If I receive a proposition to have a dialogue, I am not notified about this. 

**To Reproduce**
1. choose topic
2. state opinion
3. wait until you get a proposition for dialogue

**Expected behavior**
The icon "dialogue list" should display a notification in form of a number

**Comment by dptalks** [comment]
not a bug, a feature request.

**Comment by dptalks** [comment]
implemented.
