### ISSUE TITLE
"Decline an invite" leads to the following error messages...

### ISSUE THREAD

**Issue by MartinDPT** [digital-peace-talks/DPT-server#21]
**Describe the bug**
Decline an invite

![decline_error_1](https://user-images.githubusercontent.com/53605998/69344379-98a3db80-0c6f-11ea-83ea-4b57d4650548.jpg)
![decline_error_2](https://user-images.githubusercontent.com/53605998/69344386-9b9ecc00-0c6f-11ea-934b-03a1cda2ba28.jpg)

**Comment by dptalks** [comment]
fixed.
