### ISSUE TITLE
It looks like the icon "dialogue list" always has a notification

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#29]
**Describe the bug**
The icon to open the dialogue list always has a blue circle. This missleads users to think they have unread messages. 

**Expected behavior**
The blue cirle should only be shown when there is unread messages. 

**Additional context**
I know this is not a technical fault. But UX wise, it is a faulty design. 
Also it is likely to raise our bounce rate as it frustrates first time users. They think they should click on this icon, but when they do, nothing happens and they get even more confused.

**Comment by MartinDPT** [comment]
Solved! no message = no counter
