### ISSUE TITLE
Login (Start, Phrase)

### ISSUE THREAD

**Issue by Metin74** [digital-peace-talks/DPT-server#3]
**Is your feature request related to a problem? Please describe.**
On a device, it should be possible that multiple users can use the web app. How do we make the passphrase easy and safe for everyone?

**Describe the solution you'd like**
How can we simplify the login process?
Save and reuse passphrase should be simplified.

**Describe alternatives you've considered**

**Additional context**

**Comment by dptalks** [comment]
added copy to clipboard functionality behind the phrase on the start page and on the settings. what else?
