### ISSUE TITLE
Scrollbar-issue in long dialogs

### ISSUE THREAD

**Issue by MartinDPT** [digital-peace-talks/DPT-server#34]
**Describe the bug**
at long dialouges a scrollbar appears to scroll through the chat. saddly it get's overlayed by some UI-elements e.g. the "information-ribbon" aka class="dialogFrame"

![scrollbarissue](https://user-images.githubusercontent.com/53605998/69697011-b777f700-10e1-11ea-8f06-d6b88414fe23.jpg)

**Comment by Metin74** [comment]
done
