### ISSUE TITLE
If a proposition is accepted, user should get a notification

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#36]
**Is your feature request related to a problem? Please describe.**
I need to open the dialogue list and check manually, if my propositions got accepted. 

**Describe the solution you'd like**
1. the icon for "dialogue list" should notify my, if a proposition got accepted. 
2. Dialogues in my list could have a symbol, indicating if it is a closed, proposed or accepted dialogue. 

**Describe alternatives you've considered**
There could be like a "news ticker" where new events are described. ("A topic you created got 5 new opinions", "your proposition got accepted")

**Additional context**
We need a general approach how the user should manage their opinions and dialogues.

**Comment by dptalks** [comment]
https://github.com/digital-peace-talks/DPT-server/issues/36
