### ISSUE TITLE
Cookie should be checked with data base

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#38]
**Is your feature request related to a problem? Please describe.**
The start screen tells me "welcome back". But when I click enter, I get an error saying "user unknown"

**Describe the solution you'd like**
It should not only if I have a cookie, but if this cookie is know/valid. If I have a cookie but it is not valid, there could be a message like "Your account expired. We try to avoid it, but sometimes we need to reset everything. Click here to create a new account" which would delete the cookie.

**Describe alternatives you've considered**
If a cookie is detected, the user is automatically logged in (skip the "enter" page). If automatic log in does not work. Show a "Log In or  Sign Up" page. 

**Additional context**
Loging in is the very very first action a user does. It should run as smooth as possible.

**Comment by dptalks** [comment]
done
