### ISSUE TITLE
Dialog rating does not work

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#39]
**Describe the bug**
If I click "Yes, i want to finish the dialogue" I get an error message saying "please enter a conclusion" even so I did that

**To Reproduce**
1. Go to dialogue list
2. Click on an active dialogue
3. click "finish dialogue"
4. move the slider 
5. enter a reason for your rating
6. click "yes, I want to finish this dialogue"

**Expected behavior**
The dialogue should be finished when I click on the button.

**Additional context**
Forcing users to input text will produce very bad quality inputs.
Users that want to supply a reason will do so, users that don't want to give a reason will circumvent the mandatory input by putting in noise.

**Comment by dptalks** [comment]
done.
