### ISSUE TITLE
only one proposition per opinion

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT-server#40]
**Is your feature request related to a problem? Please describe.**
any user could spam others by sending them lots of propositions. 

**Describe the solution you'd like**
Once the first proposition was sent. The button "send proposition" should disappear. 
Additionally, it should not be possible to send more than one proposition. 

**Describe alternatives you've considered**
The user could be promted with a error message. But why show him a button if he is not allowed to click it? 

**Additional context**
If there is not many opinion, it is hard to navigate to the "proposition" button. 
If there is a lot of opinions, it is even harder to find a good view on a specific proposition button.

**Comment by dptalks** [comment]
done.
