### ISSUE TITLE
Mobile Navigation Menu (Hamburger)

### ISSUE THREAD

**Issue by Metin74** [digital-peace-talks/DPT-server#5]
**Is your feature request related to a problem? Please describe.**
How to create the Hamburger Menu and which menu entries should have Menu?

**Describe the solution you'd like**
The Hamburger menu is folded in the mobile and desktop view and can be expanded by the user by clicking on the Hamburger icon.

**Describe alternatives you've considered**
At the bottom of the screen, the navigation bar is shown in the middle.

**Additional context**

**Comment by MartinDPT** [comment]
This is not a issue this is my to do list for tomortow!
