### ISSUE TITLE
Topic positioning

### ISSUE THREAD

**Issue by Metin74** [digital-peace-talks/DPT-server#6]
**Is your feature request related to a problem? Please describe.**
Currently the topics are arranged as a table.

**Describe the solution you'd like**
The arrangement options are still being evaluated. In the future, a systematic arrangement of the topic is planned.

**Describe alternatives you've considered**

**Additional context**
An arrangement using an algorithm or artificial intelligence is possible.

**Comment by dptalks** [comment]
back engine for topic positioning is prepared.

**Comment by Metin74** [comment]
done.
